#!/usr/bin/with-contenv sh
#
# Start of apace with auto creation of subversion mod file
#
# (c) 2021 LSC-Labs
#
# Uses the vars: 
# SVN_Repositories   (Default = /home/svn)
# SVN_Areas          (If not set - no sub Areas will be created otherwise like "AreaName1;AreaName2...")
#
# avoid 'already pid is running' error
rm -f /run/apache2/httpd.pid

echo "WEB: ================================="
echo "WEB: Preparing and starting apache2..."
echo "WEB: ================================="
echo "WEB: SVN_Areas by var      : [$SVN_Areas]"

# resolve directory of this script
CurrentScript=`readlink -f "$0"`
ScriptDir=`dirname "$CurrentScript"`

Template_Folder=$ScriptDir/templates
Template_WebMod_SVN_Base=$Template_Folder/web-mod-svn-base-template
Template_WebMod_SVN_Area=$Template_Folder/web-mod-svn-area-template
Apache_WebModule_Folder=/etc/apache2/conf.d
Apache_SVN_WebModule=$Apache_WebModule_Folder/dav_svn.conf

SVN_Repo_Directory=/home/svn

echo "WEB: preparing mod file    : [$Apache_SVN_WebModule]"

cp "$Template_WebMod_SVN_Base" "$Apache_SVN_WebModule"

set -- $SVN_Areas
for strAreaName in "$@"
do 
   echo "WEB: found and creating : [$strAreaName]"
   sed 's/$(AreaName)/'$strAreaName'/g' $Template_WebMod_SVN_Area >> "$Apache_SVN_WebModule"
   mkdir -p "$SVN_Repo_Directory/$strAreaName"
   chmod -R a+rw "$SVN_Repo_Directory/$strAreaName"
done

exec /usr/sbin/apachectl -DFOREGROUND;
#exec /usr/sbin/httpd -D FOREGROUND
